# Generated by Django 3.1 on 2020-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='time_left',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
