# Generated by Django 3.0.4 on 2020-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlist',
            name='description',
            field=models.CharField(choices=[('Bot works 6h per day', 'Bot works 6h per day'), ('Max 1 bot', 'Max 1 bot'), ('Bot works 12h per day', 'Bot works 12h per day'), ('Max 3 bots', 'Max 3 bots'), ('Bot works all the time', 'Bot works all the time'), ('Max 5 bot', 'Max 5 bot')], max_length=40),
        ),
        migrations.AlterField(
            model_name='permissionlist',
            name='icon',
            field=models.CharField(choices=[('check icon', 'check icon'), ('times icon', 'times icon')], max_length=40),
        ),
        migrations.AlterField(
            model_name='permissionlist',
            name='name',
            field=models.CharField(choices=[('6h', '6h'), ('12h no', '12h no'), ('3bots no', '3bots no'), ('12h yes', '12h yes'), ('3bots yes', '3bots yes'), ('24h no', '24h no'), ('5bots no', '5bots no'), ('24h yes', '24h yes'), ('5bots yes', '5bots yes')], max_length=40),
        ),
    ]
