# Generated by Django 3.0.4 on 2020-04-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('icon', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOR BEGINNERS', 'FOR BEGINNERS'), ("I DON'T HAVE TIME", "I DON'T HAVE TIME"), ("I'M ON VACATION", "I'M ON VACATION")], default='FOR BEGINNERS', max_length=21)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=70)),
                ('max_time', models.IntegerField()),
                ('max_bots', models.IntegerField()),
                ('permission_list', models.ManyToManyField(to='sfbot.PermissionList')),
            ],
        ),
    ]
