# Generated by Django 3.1 on 2020-09-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
