# Generated by Django 3.0.4 on 2020-05-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bots',
            old_name='password',
            new_name='SF_Password',
        ),
        migrations.RenameField(
            model_name='bots',
            old_name='ac_username',
            new_name='SF_Username',
        ),
    ]
