# Generated by Django 3.1 on 2020-09-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0002_profile_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='currency',
            new_name='wallet',
        ),
        migrations.AddField(
            model_name='plan',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
