# Generated by Django 3.1a1 on 2020-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0002_auto_20200518_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='arena_status',
            field=models.BooleanField(default=False, verbose_name='Arena status'),
        ),
        migrations.AlterField(
            model_name='bots',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Bot status'),
        ),
        migrations.AlterField(
            model_name='bots',
            name='tavern_status',
            field=models.BooleanField(default=False, verbose_name='Tavern status'),
        ),
    ]
