# Generated by Django 3.1 on 2020-08-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0002_auto_20200830_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bots',
            name='converted_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bots',
            name='time_left',
            field=models.TimeField(null=True),
        ),
    ]
