# Generated by Django 3.0.4 on 2020-04-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0002_permissionlist_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
    ]
