# Generated by Django 3.0.4 on 2020-04-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0002_auto_20200419_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionlist',
            name='name',
            field=models.CharField(choices=[('6h', '6h'), ('1bot', '1bot'), ('12h no', '12h no'), ('3bots no', '3bots no'), ('12h yes', '12h yes'), ('3bots yes', '3bots yes'), ('24h no', '24h no'), ('5bots no', '5bots no'), ('24h yes', '24h yes'), ('5bots yes', '5bots yes')], max_length=40),
        ),
    ]
