# Generated by Django 3.0.4 on 2020-04-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0003_auto_20200403_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionlist',
            options={'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
    ]
