# Generated by Django 3.0.4 on 2020-05-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0003_auto_20200419_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bots',
            options={'verbose_name': 'bots', 'verbose_name_plural': 'Bots'},
        ),
        migrations.AlterModelOptions(
            name='gamesettings',
            options={'verbose_name': 'gamesettings', 'verbose_name_plural': 'Game Settings'},
        ),
    ]
