# Generated by Django 3.1 on 2020-09-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0003_auto_20200929_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_create', models.DateTimeField(auto_now=True, null=True)),
                ('currency_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfbot.currency')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sfbot.profile')),
            ],
        ),
    ]
