# Generated by Django 3.1a1 on 2020-06-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0003_auto_20200524_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='SF_Password',
        ),
        migrations.AddField(
            model_name='bots',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='bots',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='SF Password'),
        ),
    ]
