# Generated by Django 3.1 on 2020-10-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0004_auto_20200930_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='money',
            new_name='price',
        ),
    ]
