# Generated by Django 3.0.4 on 2020-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0004_auto_20200403_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionlist',
            options={},
        ),
        migrations.AlterField(
            model_name='plan',
            name='permission_list',
            field=models.ManyToManyField(related_name='permissions', to='sfbot.PermissionList'),
        ),
    ]
