# Generated by Django 3.1 on 2020-10-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0005_auto_20201005_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='cost',
        ),
    ]
