# Generated by Django 3.1a1 on 2020-06-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0005_auto_20200612_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='username',
        ),
        migrations.AddField(
            model_name='bots',
            name='SF_Username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
