# Generated by Django 3.1a1 on 2020-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0006_auto_20200612_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='bots',
            name='password',
        ),
        migrations.AddField(
            model_name='bots',
            name='SF_Password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
