# Generated by Django 3.0.4 on 2020-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0006_auto_20200403_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='special_style',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
