# Generated by Django 3.1 on 2020-10-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0006_remove_plan_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
