# Generated by Django 3.1a1 on 2020-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0007_auto_20200612_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='SF_Password',
        ),
        migrations.RemoveField(
            model_name='bots',
            name='SF_Username',
        ),
        migrations.AddField(
            model_name='bots',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='bots',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='SF Password'),
        ),
        migrations.AddField(
            model_name='bots',
            name='username',
            field=models.CharField(max_length=40, null=True, verbose_name='SF Username'),
        ),
    ]
