# Generated by Django 3.1 on 2020-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0008_auto_20201013_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan_start_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
