# Generated by Django 3.1a1 on 2020-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0008_auto_20200613_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Plan is available'),
        ),
    ]
