# Generated by Django 3.1 on 2020-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0009_auto_20201013_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
