# Generated by Django 3.1a1 on 2020-06-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfbot', '0010_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
